### ISSUE TITLE
daily balance & bees

### ISSUE THREAD

**Issue by dim-geo** [Zygo/bees#105]
Hello, is bees affected by daily balance activities in order to reduce btrfs allocated space?
I think metadata relocation would not hurt bees extent database but what about data block relocation? Is bees capable to handle this?
```btrfs balance start -dusage=50 -dlimit=2 -musage=50 -mlimit=4```
I see no mention of this in here:
https://github.com/Zygo/bees/blob/master/docs/btrfs-other.md

**Comment by kakra** [comment]
Is a rebalance even still needed with modern kernels? I used the auto-rebalance script a while ago which detects the wasted space before doing an adaptive rebalance, and it didn't do any work since a long time because wasted space stays below the threshold. I eventually retired the script completely then.

https://github.com/jtek/ceph-utils/blob/master/btrfs-auto-rebalance.rb

**Comment by dim-geo** [comment]
According to
https://btrfs.wiki.kernel.org/index.php/FAQ#Do_I_need_to_run_a_balance_regularly.3F
, it makes sense to run balance regularly on metadata with limits

Στις Κυρ, 6 Ιαν 2019, 14:07 ο χρήστης Kai Krakow <notifications@github.com>
έγραψε:

**Comment by kakra** [comment]
That FAQ is a little bit misleading. Actually, it doesn't recommend running balance unless you're seeing huge amounts of metadata space wasted. Do you see this behavior if you do not run balance for some time?

The script I linked actually does exactly that: It looks for the space wasted and if it is above a threshold (default 30%), it first cleans up empty chunks, then starts to rebalance the chunks wasting most space first and then decreasing the threshold in small steps and looping until the overall requirement is met again. This worked pretty well (and it was fast) but it stopped doing anything after a while because something in my system (kernel? bees?) just made it work properly by default.

YMMV if your btrfs is very full most of the time (I guess above 75%-80% space used).

**Comment by dim-geo** [comment]
Ok thanks for the info, however the initial question is not clarified. Is balance 'compatible' with bees?
If not, for sure it must be mentioned in the documentation because many users might run balance to deallocate space.

**Comment by Zygo** [comment]
Balance was documented up until e8298570ed09341b2531c7952b0f341604d39472 when...(((apply retroactive rationalization))) it was removed from the list of feature interactions because the list was far too long for casual reading and the interaction between bees and balance is fairly 'normal' anyway.  (((end retroactive rationalization)))  Or, more likely, I just dropped it accidentally while editing.  :-P

Balance makes copies of extents and deletes the originals.  bees will scan the data in its new location on some future crawl.  Along the way, bees will notice that the old data is no longer accessible in the old locations and will remove the old hash table entries.  The removal happens just before the new data is inserted, so there's (little to) no impact on hash table occupancy or hash table entry lifetimes (depending on how overcommitted the hash table was).  For normal maintenance balances (less than 0.1% of the total filesystem data) this is just a quick reread of the fraction of the filesystem that was balanced.  This is the same way bees normally handles new data and deleted old data.

If you're going to run a full balance (e.g. for RAID profile conversion) it may be a good idea to restart bees with an empty hash table (i.e. delete `beeshash.dat` and recreate) after the balance is done.  A full balance invalidates the entire hash table and gives every extent new transids, so bees will be forced to do a full rescan of the data (even if you keep `beescrawl.dat`, the set of data covered by previous scans will be empty).  If there's nothing in the hash table, then bees won't waste any time proving the hash table contents are invalid.

**Comment by kakra** [comment]
Or in other words: Simply don't run balance unless you really need to... :-?

**Comment by Zygo** [comment]
For the larger btrfs balance questions:

_Never_ balance metadata unless you have to (e.g. working around old `ssd` mount option bugs, adding an odd number of devices, changing RAID levels).  Metadata balances are slow even on solid-state media, and while they're not dangerous in and of themselves, metadata balances increase the risk of the filesystem running out of metadata space in the future.  In particular, never run that default cronjob (which still appears in several popular distros) that runs `btrfs balance start -musage=30`!

The theory is that if your filesystem ever needed a byte for metadata in the past, it's reasonable to expect the filesystem will need that byte for metadata in the future, and you never, ever, _ever_ want to run out of metadata space on btrfs.  Running out of metadata space is very different from running out of data space:  you can run out of data space all day long and the only bad thing that happens is a few applications get `ENOSPC`--but if you run out of metadata space, your filesystem becomes abruptly read-only, and can be difficult or impossible to mount again.

Thus, the best strategy is to keep all the unused metadata space your filesystem has allocated in case the filesystem needs it again, and you do that by never balancing metadata.  That way the filesystem can put metadata in space it's already allocated instead of trying (and possibly failing) to allocate new metadata chunks.  An extra 1% or 2% of disk space use is much cheaper than random downtime.

The kernel has improved over the years to need balance less often; however, the reality is the kernel no longer does stupid things it used to do that you could _only_ fix by balancing.

Data balances are still useful, and they do two things:

1.  Defragment free space, which makes allocation of free space slightly faster (though maybe not fast enough to pay for the IO cost of balance).
2.  Ensure that there are unallocated data chunks on the filesystem so that future metadata allocations won't fail (see above, you never want a metadata allocation to fail).

To achieve goal 1, you need to inspect more deeply than the standard `btrfs-progs` provide, so that you run balance only on block groups that are heavily fragmented, and leave less-fragmented groups alone.  https://github.com/knorrie/python-btrfs/tree/master/examples has some example scripts that balance selectively where it's really required.

To achieve goal 2, you need to balance data blocks until every disk has at least one unallocated chunk.  You can process the output of `btrfs fi usage --raw` with a script that determines how much space is unallocated, then run the balance if the disks have too little unallocated space.  You could also just run `btrfs balance start -dlimit=1` once a day, as that is usually close enough to the 'correct' behavior.

If you have sufficient unallocated space for goal 2, and your free space fragmentation is low enough for goal 1, then you don't need to run balance today, but check again tomorrow.

**Comment by dim-geo** [comment]
@Zygo I am interested to create a python balance like the one you describe.

```
To achieve goal 1, you need to inspect more deeply than the standard btrfs-progs provide, so that you run balance only on block groups that are heavily fragmented, and leave less-fragmented groups alone. 
```

Can you please elaborate more on 'fragmented'? Imagine the scenario where I  have 2 block groups that are 50% used. Which block should be balanced first?
Do I need to consider the size of the block group? the number of extents into it?
in other words, what are the criteria for sorting balance groups for balance actions? (size of block group, used percentage, number of extents)

Of course after each balance, you should recheck the list.

**Comment by kakra** [comment]
@dim-geo There's also a collection of examples using a python lib here, including a starting point for your idea:
https://github.com/knorrie/python-btrfs/blob/master/examples/balance_least_used.py

**Comment by Zygo** [comment]
> https://github.com/jtek/ceph-utils/blob/master/btrfs-auto-rebalance.rb

I would not use that script.  It has `usage=0` which hasn't been needed for years (since kernels in the late 3.x series).  It also invokes `btrfs balance start -m`, which means it could balance metadata, and you never want to balance metadata.

**Comment by dim-geo** [comment]
I have created this:

It balances x number of data chunks starting from lowest to highest. After every balance it recalculates the next chunk to be balanced. If the size of the chunk to be rebalanced is higher than the free space of the next to be rebalanced chunk, it stops balancing. I think it's ideal to run on a daily basis to balance a couple of chunks.

https://github.com/dim-geo/btrfsbalancer/tree/master
