### ISSUE TITLE
Bees don't free FD, so deleted files are still use space

### ISSUE THREAD

**Issue by Nefelim4ag** [Zygo/bees#18]
I did some tests with bees with NFS share for VM's,
so i clone VM's several times and after some time delete it,
but bees didn't finish deduping, and after 24h space not freed and bees continue deduping deleted data.

So, may be you can add some code, to free FD of deleted file?
P.S. as bees show "(deleted)" in the log, bees understand when file already deleted and if i understand correctly, can free FD.

Thanks.

**Comment by Zygo** [comment]
The log message code just asks the kernel for a filename, and the kernel adds the " (deleted)".  bees doesn't look at the names, and can't trust the name supplied by the kernel after the file is opened.

After the last link to a file is deleted, its inode and data continue to exist as long as some process has an open FD.  bees itself is preventing the file from being removed from the filesystem.

bees could forcibly close all cached non-temporary FDs every 15 minutes, like it does in the workaround for subvol FDs.  That would limit the time bees could hold a FD open, and deleted files would be removed sooner.

Complicating matters further, the temporary files used by bees start out in the deleted state (they are created with O_TMPFILE so they disappear after they are closed).  I'm not sure what to do with the temporary FDs.  They share the FD cache because they can show up in scan and dup hit results, and we don't want to close them while they're still in use because the extent rewriting code relies on them.  On the other hand I'm not sure that bees needs to put the temporary FDs in the global FD cache.

I'll try the same "close all open files every 15 minutes" approach that the subvol FD cache uses, and see what breaks.
