### ISSUE TITLE
Compile issue (-Werror=unused-result)

### ISSUE THREAD

**Issue by linuxrrze** [Zygo/bees#2]
Hi,

I just tried to build debian packages for bees, and I'm running into the following
compile issue. Yes, I know the warning could be ignored, but most build services
apply very restrictive compiler options to force the best code quality, so it'd be
nice to have this warning/error fixed:

<...>
[  132s] g++ -Wall -Wextra -Werror -O3 -I../include -ggdb -fpic -std=c++11 -Wold-style-cast -o execpipe.o -c execpipe.cc
[  133s] execpipe.cc: In function 'crucible::Fd crucible::popen(std::function<int()>, std::function<void(const crucible::ResourceHandle<int, crucible::IOHandle>&)>)':
[  133s] execpipe.cc:81:38: error: ignoring return value of 'int system(const char*)', declared with attribute warn_unused_result [-Werror=unused-result]
[  133s]     system("ls -l /proc/$$/task/ >&2");
[  133s]                                       ^
[  133s] cc1plus: all warnings being treated as errors
[  133s] Makefile:34: recipe for target 'execpipe.o' failed
[  133s] make[2]: *** [execpipe.o] Error 1
[  133s] make[2]: Leaving directory '/usr/src/packages/BUILD/lib'

Thanx,
   Marcel

**Comment by uroni** [comment]
Werror should only be set for development, because new warnings pop up with new GCC versions all the time

**Comment by Zygo** [comment]
Bees has only ever been tested with one building environment until last week.  That means bees is still very sensitive to changes in toolchain and build options.  I once spent several hours chasing a subtle bug in the time interval code that was masked by using -O3 instead of -O0.  For now I'd prefer to receive reports of new warnings and fix them instead of simply ignoring potentially serious operational problems.

This code looks like a leftover from one of the earlier prototypes.  The real fix is to just remove the offending function, but deleting crucible::popen leads to a cascade of missing dependencies in the unit tests, so it's not a trivial patch.

Bees itself doesn't need to spawn child processes any more, so simply removing the offending code in crucible::popen will not break the bees binary.  Removing -Werror would work too.
