### ISSUE TITLE
Seems to crawl the same two files over and over again

### ISSUE THREAD

**Issue by kakra** [Zygo/bees#27]
Currently I see bees crawling the same two files over and over again since days. It seems to be constantly reading those files without any progress (always offset 0), and it generates 100% CPU during the process due to constantly hashing the same blocks.

This is from the logs:

```
Okt 27 19:26:26 jupiter beesd[714]: crawl: Crawled inline 1 data 0 other 121 unknown 0 gen_low 1 gen_high 0 BeesCrawlState 857:271 offset 0x35894488 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago) in 0.001s
Okt 27 19:26:26 jupiter beesd[714]: crawl: Crawling BeesCrawlState 857:271 offset 0x35894488 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Crawl empty BeesCrawlState 857:271 offset 0x35894488 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Deferring next transid in BeesCrawlState 857:271 offset 0x35894488 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Next transid in BeesCrawlState 1002:0 offset 0x0 transid 1266978..1267007 started 2017-10-27-19-03-16 (908s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Restarting crawl BeesCrawlState 1002:0 offset 0x0 transid 1266978..1267007 started 2017-10-27-19-03-16 (908s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Crawling BeesCrawlState 1002:0 offset 0x0 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Crawl empty BeesCrawlState 1002:0 offset 0x0 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Deferring next transid in BeesCrawlState 1002:0 offset 0x0 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Next transid in BeesCrawlState 1844:5330 offset 0x1 transid 1266978..1267007 started 2017-10-27-19-03-16 (908s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Restarting crawl BeesCrawlState 1844:5330 offset 0x1 transid 1266978..1267007 started 2017-10-27-19-03-16 (908s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Crawling BeesCrawlState 1844:0 offset 0x0 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Crawling 60 results from BeesCrawlState 1844:0 offset 0x0 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Crawled inline 1 data 45 other 14 unknown 0 gen_low 17 gen_high 0 BeesCrawlState 1844:5332 offset 0x1 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago) in 0.001s
Okt 27 19:26:26 jupiter beesd[714]: crawl: Next transid in BeesCrawlState 1849:0 offset 0x0 transid 1266978..1267007 started 2017-10-27-19-03-16 (908s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Restarting crawl BeesCrawlState 1849:0 offset 0x0 transid 1266978..1267007 started 2017-10-27-19-03-16 (908s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Crawling BeesCrawlState 1849:0 offset 0x0 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Crawl empty BeesCrawlState 1849:0 offset 0x0 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Deferring next transid in BeesCrawlState 1849:0 offset 0x0 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Next transid in BeesCrawlState 258:0 offset 0x0 transid 1266978..1267007 started 2017-10-27-19-03-16 (908s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Restarting crawl BeesCrawlState 258:0 offset 0x0 transid 1266978..1267007 started 2017-10-27-19-03-16 (908s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Crawling BeesCrawlState 258:0 offset 0x0 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Crawl empty BeesCrawlState 258:0 offset 0x0 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Deferring next transid in BeesCrawlState 258:0 offset 0x0 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Next transid in BeesCrawlState 261:0 offset 0x0 transid 1266978..1267007 started 2017-10-27-19-03-16 (908s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Restarting crawl BeesCrawlState 261:0 offset 0x0 transid 1266978..1267007 started 2017-10-27-19-03-16 (908s ago)
Okt 27 19:26:26 jupiter beesd[714]: crawl: Crawling BeesCrawlState 261:0 offset 0x0 transid 1267007..1267034 started 2017-10-27-19-18-24 (0s ago)
```

The state file switches between both files every few seconds:

```
THREADS:
        tid 783: [83957s] main
        tid 849: crawl: searching at offset 0x159000 in file /run/bees/mnt/bc201ce5-8f2b-4263-995a-6641e89d4c88/home/kakra/.local/share/Steam/userdata/126535081/310560/remote/savegame@profile_backup#QKIGMYYI.LKR
        for BeesBlockData { 4K 0x1cb000 fd = 34 '/run/bees/mnt/bc201ce5-8f2b-4263-995a-6641e89d4c88/home/kakra/.local/share/Steam/userdata/126535081/310560/remote/savegame@profile_backup#QKIGMYYI.LKR', data[4096] = '\xad\xacB\x07H}\xe8Kl\x83\x0bQ...' }
        tid 850: status: writing status to file '/run/bees//bc201ce5-8f2b-4263-995a-6641e89d4c88.status'
        tid 851: crawl_writeback: [246s] BeesCrawlState 259:6594754 offset 0x1 transid 1267021..1267048 started 2017-10-27-19-26-26 (401s ago)
        tid 853: hash_writeback: [9.874s] flush rate limited at extent #18 (18 of 61)
        tid 854: hash_prefetch: [989.118s] idle 3600s

THREADS:
        tid 783: [83998s] main
        tid 849: crawl: searching at offset 0x119000 in file /run/bees/mnt/bc201ce5-8f2b-4263-995a-6641e89d4c88/home/kakra/.local/share/Steam/userdata/126535081/310560/remote/savegame@profile#QKIGMYYI.LKR
        for BeesBlockData { 4K 0x1d9000 fd = 34 '/run/bees/mnt/bc201ce5-8f2b-4263-995a-6641e89d4c88/home/kakra/.local/share/Steam/userdata/126535081/310560/remote/savegame@profile_backup#QKIGMYYI.LKR', data[4096] = '\xad\xacB\x07H}\xe8Kl\x83\x0bQ...' }
        tid 850: status: writing status to file '/run/bees//bc201ce5-8f2b-4263-995a-6641e89d4c88.status'
        tid 851: crawl_writeback: [287.023s] BeesCrawlState 259:6594754 offset 0x1 transid 1267021..1267048 started 2017-10-27-19-26-26 (442s ago) (dirty)
        tid 853: hash_writeback: [8.709s] flush rate limited at extent #22 (21 of 61)
        tid 854: hash_prefetch: [1030.14s] idle 3600s

THREADS:
        tid 783: [84038s] main
        tid 849: crawl: searching at offset 0x1f9000 in file /run/bees/mnt/bc201ce5-8f2b-4263-995a-6641e89d4c88/home/kakra/.local/share/Steam/userdata/126535081/310560/remote/savegame@profile#QKIGMYYI.LKR
        for BeesBlockData { 4K 0x1e7000 fd = 34 '/run/bees/mnt/bc201ce5-8f2b-4263-995a-6641e89d4c88/home/kakra/.local/share/Steam/userdata/126535081/310560/remote/savegame@profile_backup#QKIGMYYI.LKR', data[4096] = '\xad\xacB\x07H}\xe8Kl\x83\x0bQ...' }
        tid 850: status: writing status to file '/run/bees//bc201ce5-8f2b-4263-995a-6641e89d4c88.status'
        tid 851: crawl_writeback: [327.041s] BeesCrawlState 259:6594754 offset 0x1 transid 1267021..1267048 started 2017-10-27-19-26-26 (482s ago) (dirty)
        tid 853: hash_writeback: [6.538s] flush rate limited at extent #25 (24 of 61)
        tid 854: hash_prefetch: [1070.16s] idle 3600s
```

What changes over time is the transid range...

I don't think something is accessing the files all the time:

```lsof|fgrep savegame``` yields nothing. Timestamps (atime, ctime, and mtime) are weeks ago, eventually even months.

**Comment by kakra** [comment]
After some system updates involving many file updates and a system overload (by accident, load >400 for several minutes, the system recovered successfully), the problem seems to be gone.

I think there is some bug in the crawler which sometimes does not cleanup all files, and there are situations which can trigger successfully cleaning it up later.

**Comment by Zygo** [comment]
Well...the crawler is the crawler...

Assuming no bugs, the bees crawler consumes exactly the set of new extents reported by btrfs.  That set contains lot of unexpected things at the best of times (especially if defrag, autodefrag or balance is used), but it also contains extents that were modified by bees itself.  This can create a feedback loop.  Bees avoids doing things that directly result in feedback loops, but they can still happen.

Your logs don't show a feedback loop, though.  Bees explicitly logs any use of the dedup ioctl, but the log excerpts you posted don't show any, and the status snapshots don't involve files that bees writes to directly.

I wonder if you can snapshot the event counters while this happens (if it should happen again) to see whether we're reading blocks or doing something else with the 100% CPU time.

It doesn't seem to be data-dependent.  CRC64 collisions generate their own log messages (with all-caps "HASH COLLISION" in them).  Hash table page overflow wouldn't explain the crawler's behavior (it would trigger a lot of reading other files to compare them, but such comparisons would normally only happen once as the crawler will not read a subvol/inode/offset tuple twice).

**Comment by kakra** [comment]
I'll record the events counters next time I see such a problem. Thanks.

I think we can close this issue until the problem shows up again.

**Comment by kakra** [comment]
Well, here we go:
[bees-logtrace.zip](https://github.com/Zygo/bees/files/1439033/bees-logtrace.zip)

It's stuck on the same two files again, and consumes more than 90% CPU constantly (distributed across multiple threads, percents relative to one core).

**Comment by kakra** [comment]
BTW: I just "btrfs filesystem defrag" the two files, and now the crawler continues to work on other parts of the filesystem that it didn't touch yet.

**Comment by kakra** [comment]
I had a few other occasions where bees looped over the same files over and over again, and fixed that problem with "btrfs fi defrag", too. Since then, I didn't see this behavior again.

Any idea what could cause this?

**Comment by Zygo** [comment]
Most of the event trails bees-logtrace.zip end at replacedst_same, where bees has found a dedup candidate, but the candidate's src block in the same extent as the dst block, so no dedup can be done without splitting the extent first.  Currently bees tries to avoid that extent split because it excessively fragments VM image files and exacerbates btrfs's backref performance issues.

I guess these files have a lot of repeating 4K blocks in them?  bees appears to be doing a lot of matches like this (5037913 times over the time period covered by your logs).  This would include rereading and recomputing CRC for each match for extra slowness.

A caching layer for block data and CRCs would help at least as much as preventing bees from rereading block data 5 million times (it could use cached values instead).  I plan to implement a caching layer anyway for other reasons.

It might be easier to fix this one just by checking the extent boundary (bytenr..bytenr + offset) against the address returned from the DDT and rejecting any match in the same extent before going into the loop to resolve the address, since there are only two cases where a matching block appears in the same physical extent:

 * the DDT is pointing to the same physical block the scanner is, so no action needs to be taken,
 * the DDT is pointing to a different physical block in the same physical extent, so no action can be taken.

Defrag would appear to temporarily fix this because it would move the data to a new physical location, invalidating the saved physical location in the DDT hash table so bees can't find the matching blocks any more.  If the extent layout is not reproduced exactly after defrag, then bees may be able to find matching blocks on different extents and complete the dedup.

**Comment by kakra** [comment]
Indeed, the affected files have many duplicate 4k blocks, even so much that the toxic hash limiter kicks in. So, I guess a check for the extent boundary would be best, including an event counter that this happened. If you point me to the responsible source file and function, I could try to implement it. I just cannot test it currently as I no longer see that.

**Comment by kakra** [comment]
I think there are two function where this could be implemented:

1. BeesContext::scan_one_extent
2. BeesResolver::replace_dst

I'm not sure if there's already an "#if 0"'ed check for it in number 1.

**Comment by Zygo** [comment]
The #if 0 check only works for compressed extents...but it does work for those.

For uncompressed extents we need to find the extent bytenr which contains the physical block in the saved src addr.

In replace_dst we will have the forward extent refs for the dedup src candidates, and those refs do contain the extent bytenr of the src block.  We get to replace_dst very late in the loop at scan_one_extent, though, so we'd end up repeating a bunch of work.

It could also be done by searching tree 2 (the extent tree) directly with TREE_SEARCH_V2.

**Comment by Zygo** [comment]
This is now a little worse with the extra concurrency and transid-driven crawl scheduling, which sets up the conditions to reproduce this more often.

If two extents are scanned at the same time, and they have duplicate data, both extents can be added to the dedup table as unique blocks.  Later, if there are many copies of the data, some of the copies are deduped with one of the DDT entries and some with the other.  All of these modified duplicates then appear new to later runs of the scanner, so the process repeats until something perturbs the data and eliminates one of the dedup candidates, breaking the loop.

This ends up on the same large pile of known issues with the current scanning algorithm.  When identifying duplicate blocks, the scanner Task must lock all extent bytenrs involved (with an appropriate deadlock resolution algorithm) to prevent other Tasks from modifying them until after all updates to the filesystem and hash table are completed.  Currently there is a single lock because the deadlock resolution algorithm is missing, and there is no locking in place to prevent duplicate insertions to the hash table.

**Comment by kakra** [comment]
I think I'm currently seeing it with the 4 large VDI files (Virtualbox disk images) I have. It's walking over the files since days. The transid range in the crawl state file progresses, and the file offsets in the dedup logs also progress. But in the end it just rewinds in a new transid range and starts from the beginning.

**Comment by kakra** [comment]
Am I right that using `--scan-mode=1` has an advantage here? For now I'm using that with `--thread-factor=0.5`, let's see what happens...

**Comment by Zygo** [comment]
scan-mode 1 does not attempt to keep the extent refs clustered as much as scan-mode 0 does, so it may be less susceptible to colliding duplicate data lookups.

It depends on whether there are duplicates in the filesystem because the same file appears slightly modified in several snapshots (where mode 0 makes them collide) or if the duplicates are scattered over separate files located close together in the subvol tree (where mode 1 makes them collide).

When there are only a few extents left to scan, either scan mode will have problems because they will submit all new extents in the filesystem to the worker queue within a second or less.  If the filesystem is otherwise idle these extents become the only new extents in the next scan, so the process repeats.

`--thread-count=1` should avoid the new race conditions, but with a significant performance impact, and other causes of this issue are not resolved (note that the logs at the top of this issue came from a single-threaded version of bees).

**Comment by Zygo** [comment]
My current top-of-head thinking is that `scan_forward` needs to be broken down into phases:

1.  Collect all block sums from incoming extent
2.  Look up all block sums in the hash table, using a new "atomic lookup and insert" method so that copies of data in different extents are visible during the lookup phase
3.  Look up all block addresses found in the btrfs extent tree to map them to bytenrs (alternate: change hash table format to encode bytenr in the hash table)
4.  If any of those were already locked, unlock all the bytenrs we locked, and reschedule the current Task after the lock that we couldn't get is released
5.  Once we have all the locks, do dedup or extent rewrite with impunity
6.  Delete blocks from the dedup dst extent from the hash table
7.  Release all locks, destroy Task, schedule any Tasks that were deferred in step 4.

Step 4 skips over any extents that may be colliding, and lets bees move forward processing unrelated extents.

Currently bees only locks the extent that was passed to `scan_forward`, and blocks the Task (so the worker thread is idle) when a lock is found.  Lots of room for improvement there.

**Comment by kakra** [comment]
BTW: How do you recover from buggy behavior that manifested in the hash table - like now having duplicate hash entries? And did Bees already have hash table format changes? How are these handled?

Speaking of performance, I'm currently experimenting with loadavg thresholds to suspend the threads for a while. If you'd like, you can review it in my integration branch but it's not final yet. The idea is to have something like a throughput mode and an adaptive background mode in Bees. My use case is to have Bees throttle itself during games or other latency sensitive workloads. Bees manages to put a lot of IO load on the filesystem which really hurts processes that need good IO latency. Loadavg is not the best way to do it, because it measures both CPU load and IO load (original Unix semantics only measured CPU load). Is there a way to measure IO load in Linux, any ideas? To not further hijack this thread, maybe comment on the commit there. ;-)

**Comment by Zygo** [comment]
It takes a lot to hurt the bees hash table.  Duplicate entries just end up being stored in a set during retrieval, which eliminates them.  Bad data is the same as old good data that is out of date--it makes bees slower, but doesn't affect correctness.  Bad does take up extra space, but that has the same effect as making the table smaller--it slightly increases the probability that a hash won't be found.

So far all hash table format changes have used bits that were previously 0--there are 12 at the low end of every extent address and a few bits at the top (e.g. nobody has 16EB btrfs filesystems, so we could repurpose bit 63 of a block address to carry some extra information).  There are maybe 5 or 10 bits left, or as many as 20 if we use one of the bits as a "version" field that invalidates the bits already in use.

Anything more than that will require an incompatible format change.

**Comment by kakra** [comment]
The 12 bits are due to 4k block alignment? That probably won't work out well on platforms that use non-4k block sizes with the lowest bits having a higher probability of really being unused.

**Comment by Zygo** [comment]
I don't know of any platforms that btrfs can run on with a page size _smaller_ than 12 bits.  Larger block sizes are no problem for the hash table format.  As long as they're a multiple of 4K, the bottom 12 bits will always be zero.  Such sizes could be a problem for the rest of the dedup logic which assumes dedup alignment and page size are also 4K, but as long as these three sizes are all the same, it should be a matter of changing a few #defines to work.

**Comment by kakra** [comment]
While I didn't try scan mode 2 yet, the "brown paper bag" fixes fixed it. Thanks.

Commit 087ec26c44a73c4207c0a7281d8974e3360054ff
Commit 6aad12424191f01a655507a44a30aca61330e910
