### ISSUE TITLE
Relative reliability on read-only snapshots w.r.t. duperemove

### ISSUE THREAD

**Issue by HaleTom** [Zygo/bees#32]
I use the excellent [btrbk](https://github.com/digint/btrbk/) to take snapshots (which are read-only), and `send` them to an external disk.

I see in the [Bad Btrfs Feature Interactions](https://github.com/Zygo/bees/#bad-btrfs-feature-interactions):
> * btrfs read-only snapshots (never tested, probably wouldn't work well)

I'm currently using [duperemove](https://github.com/markfasheh/duperemove) whose [man page](https://manned.org/duperemove#head5) says:
>
       -A     Opens files readonly when deduping; currently requires root
              privileges (and is enabled by default for root). Allows use on
              readonly snapshots or when the file might be open for exec.

I've never had a problem using `duperemove -A` with read-only snapshots.

Should using `bees` be just as reliable as `duperemove -A`? 

Does it use any different system calls to dedupe other than `duperemove` which uses the Linux kernel extent-same ioctl?

**Comment by Zygo** [comment]
bees always acts like the description of duperemove -A, i.e. files are opened by root readonly, and the extent-same ioctl is used to dedup them.

As far as I know there is no reliability difference, i.e. if duperemove triggers a bug that crashes your kernel, so can bees, and vice versa.  The differences between bees and duperemove are mostly in the design of the hash table and the incremental scanning method.

As far as I know the restriction applies to an older version of bees that didn't work this way (years ago), and a quick test shows it works fine.  I should update the doc to remove that line.

There could be a theoretical problem if you run bees and btrfs incremental send at the same time, related to changing the physical layout of the filesystem while incremental send is running.  The same kind of problem would occur if you ran balance/device-delete and incremental send at the same time.  I don't know the nature of that problem should it exist (kernel oops, hang, aborted send, aborted receive, etc) though it should not corrupt any data by itself.

bees uses a different set of ioctls than duperemove, especially LOGICAL_INO, TREE_SEARCH_V2, and INO_PATHS (all btrfs-specific and all require root).  bees does not use the FIEMAP ioctl, so bees doesn't need the duperemove options to avoid FIEMAP performance issues.

**Comment by HaleTom** [comment]
Excellent, thanks for your detailed response, and the upcoming doc updates!

You don't use `LOGICAL_INO_V2` as mentioned [here](https://patchwork.kernel.org/patch/9966745/)?

**Comment by kakra** [comment]
I think this can be closed: As of v0.5, the README covers this exact issue and converts it into a non-issue in commit dc736039. ;-)

**Comment by Zygo** [comment]
Agreed, I will close.

To answer HaleTom's earlier question:

bees up to v0.5 has some significant architectural problems because it cannot consume the extent tree directly.  There are a lot of hacks to deal with incomplete information from multiple subvol (extent ref) trees, and even a few snapshot rotations can overwhelm the crawler.  LOGICAL_INO_V2 is the missing piece that allow bees to crawl the extent tree directly and efficiently; however, the scanner, crawler, and resolver components (i.e. most of the working parts of bees) all need to be redesigned to operate in the opposite direction (i.e. working from extents to extent refs instead of the other way around).

Historically bees has avoided calling LOGICAL_INO v1 as much as possible.  When LOGICAL_INO_V2 support is done, the resulting code will call LOGICAL_INO_V2 at least once for every unique extent.  It will not perform well on kernels before v4.14 (the first kernel where LOGICAL_INO_V2 is available).

I haven't decided yet whether bees will have a fallback capability to use LOGICAL_INO v1, or if there will just be a flag day when the next bees release stops running on kernels before v4.14 (i.e. LOGICAL_INO_V2 becomes mandatory).  That decision is probably a year away though.
