### ISSUE TITLE
[RFC] May be add some default sh wrapper?

### ISSUE THREAD

**Issue by Nefelim4ag** [Zygo/bees#4]
What's about do something like, by default:
1. Store binary and table at /var/lib/bees
2. Have a config at /etc/bees.conf
3. Add a sh/bash file at bin/bees for wrap default config
---
May be add some options to config for automount FS based on UUID and run bees in background?
(I think, it's can work pretty well with systemd restriction and private mount points)

Or you want write all of this stuff in code?

Thanks for any comments.
P.S.
Patch are welcomed?

**Comment by Zygo** [comment]
Patches are welcome.  Figuring all this stuff out so I don't have to is also welcome, even without code.  ;)

One thing to consider is the case where the deduped filesystem is encrypted.  The log file leaks  metadata (and a little data) information from the filesystem, and the hash table is just millions of "this hash can be found at this physical address" leaks.

To contain the leakage, I set up bees instances to store both hash table and log files on the same filesystem that is being deduped.  Unfortunately there's no one-size-fits-all way to do that.  I create a subvol at "/beeshome" in each btrfs, and put BEESHOME and the log file there.  It may not be the best convention, but up until a week ago it was the *only* convention used in bees installations.  ;)

On the other hand, maybe there are only two cases:  

1. BEESHOME embedded in the deduped  filesystem
2. BEESHOME in /var/lib/bees (or any other default system-wide location).

In that case, it would be reasonable to set up case 2 by default, since case 1 is non-trivial and probably has to be changed to fit the requirements of the specific site anyway.

**Comment by Nefelim4ag** [comment]
Thanks, so i work on the proof of concept.

---
If support of custom solutions is really needed, i.e. for store data on crypted volumes, i have a idea how make this thing common.
/* For this i think about custom config files i.e. config per volume, (i do something like it in  [Ananicy](https://github.com/Nefelim4ag/Ananicy)) */
