### ISSUE TITLE
Potential sensitive data leak

### ISSUE THREAD

**Issue by kakra** [Zygo/bees#53]
Bees should not expose potential sensitive data to the logs by default, that is the "data[]" parameter spooled to the logs. While that may be interesting while developing and running on test data, bees should really not do that by default.

I propose to introduce a cmdline parameter which enables exposure of such data, and it should not have a short option, maybe giving it a speaking name like "--expose-sensitive-data".

What do you think?

**Comment by Zygo** [comment]
Maybe `--log-data` and `--log-filenames`?  Makes it clearer what is being logged in each case, and in some cases even filenames are sensitive.  We can turn off name_fd in places like BeesFileRange so the logs contain only inode numbers (which can be looked up with `btrfs ins ino` later if required).

OTOH maybe the default should be something like `--no-log-data --log-filenames` (which implies these both have '--no' variants) since people probably do expect filenames logged.  Which is messy since the options wouldn't all default the same way...it's not overwhelmingly clear that my proposal is better than yours here.

I do recommend keeping the logs in files accessible only to root, and on the same filesystem that is to be deduped, so the attack surface of the log data is roughly equivalent to the attack surface of the file data.  They're not quite equivalent though, and I can't think of another tool that logs the file data off the top of my head.

**Comment by kakra** [comment]
Well, we could name the option `--dont-log-data` and `--log-filenames` representing the defaults, and then prefix it with `--no-` to reverse the option.

Another idea could be to use `--log-details=filenames,nodata` and then one could just run with `--log-details=nofilenames` to also silence filenames.

**Comment by Zygo** [comment]
Given that:

 * Nobody(tm) expects file data to appear in logs,
 * Everybody(tm) expects or is at least not surprised by file names appearing in logs, and
 * the file content data is really only interesting to bees developers

then maybe it would be simpler to just #if 0 out the data log (as that was all you initially asked for), and not add runtime options to control it at all.

The BeesData interface is bubbling up to the top of my TODO list, so if we added an option now, I'd just end up having to implement it again in BeesData's replacement...or I could decide now to drop the feature entirely.

**Comment by kakra** [comment]
Then let's just wait until BeesData bubbled up far enough. ;-)
