### ISSUE TITLE
System Hangs

### ISSUE THREAD

**Issue by Nefelim4ag** [Zygo/bees#6]
Hi, i just give a try to bees on my notebook, i have only one btrfs partition for all data.

After some processing, my system hangs not completely but looks like btrfs thread are hung and i don't see something in the dmesg (and i can't execute any command, as a IO Hung).

After reboot and short time i get this hang again, so looks like a problem with part of fs (but i catch it only by bees).

After reset system, i get a corrupted kernel image and to fix this, i must boot from iso and reinstall kernel.
So it's a expected behavior? I think what extent_same can't corrupt any data -_-'.

May be it's a bad idea run bees on the root partition?

Archlinux x86_64
Linux 4.8.10
Bees - latest git

---
Update:
I leave it's working for several hours (~10h), and system not hangs, or may be hungs is a just long btrfs transactions. But after reboot i get corrupted kernel image again =\
Thoughts?

**Comment by Zygo** [comment]
extent_same cannot corrupt data, but it can't fix metadata that was already corrupted either.  If there is already metadata corruption on the disk, bees will certainly cause the kernel to trip over it.  Bees reads every non-inline data extent on the filesystem, and a crash will make bees restart at the last checkpoint, so on next startup bees will push the kernel to almost immediately crash again.  This can only be fixed by repairing the filesystem.

If you are able to `cat /proc/<pid>/stack` (or `cat /proc/<bees-pid>/task/*/stack`) you can get a kernel stack trace for the hanging processes which may provide a clue about where things are blocking.  If the operations are affecting bees, there will be log messages tagged with `PERFORMANCE` or `WORKAROUND`.  These tags trigger on any operations that take more than a few seconds, and don't necessarily indicate a problem.

I run millions of extent_same operations per day across several machines.  extent_same has a lower failure rate than e.g. fsync() or write(), but I do enough testing to see a failure rate above zero on all of these operations on btrfs.  :-(

**Comment by Nefelim4ag** [comment]
May be you right about metadata corruption, btrfs check show some strange errors about abandoned data
I recreate my subvolumes with data, and at now bees logs looks much more pretty %)
i don't see much of exceptions, so i will let it run for some time

Thanks.

**Comment by Nefelim4ag** [comment]
So, as i don't think it's a Bees problem, i will close issue.
