### ISSUE TITLE
[v0.6] stl_tree.h:1020:25: error: macro swap requires 2 arguments, but only 1 given

### ISSUE THREAD

**Issue by kakra** [Zygo/bees#85]
A Gentoo user reports an issue against v0.6 that I cannot reproduce. Additional information is here:
https://bugs.gentoo.org/670606

@Zygo Maybe related to gcc-8? I don't use gcc 8 yet.

The gist is:

```
                 from ../include/crucible/fs.h:16,
                 from fs.cc:1:
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_tree.h:1020:25: error: macro "swap" requires 2 arguments, but only 1 given
       swap(_Rb_tree& __t)
                         ^
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/stl_tree.h:1598:59: error: macro "swap" passed 10 arguments, but takes just 2

  -------------------------------------------------------------------

  This is an unstable amd64 chroot image at a tinderbox (==build bot)
  name: 17.0-desktop-gnome_libressl_20181104-213057

  -------------------------------------------------------------------

gcc-config -l:
 [1] x86_64-pc-linux-gnu-8.2.0 *

Available Python interpreters, in order of preference:
  [1]   python3.6
  [2]   python2.7 (fallback)
  [3]   jython2.7 (fallback)
Available Ruby profiles:
  [1]   ruby23 (with Rubygems) *
java-config:
The following VMs are available for generation-2:
*)	IcedTea JDK 3.9.0 [icedtea-bin-8]
Available Java Virtual Machines:
  [1]   icedtea-bin-8  system-vm

emerge -qpvO sys-fs/bees
[ebuild  N    ] sys-fs/bees-0.6  USE="-tools"
```

**Comment by Zygo** [comment]
It looks like one of the #includes before <set> is defining a macro named `swap` that then breaks the C++ header.  It would depend on what's in the build environment.

If we change the header order then we probably fail to build later when we try to use the swap function.

I think this needs to be fixed in the build environment.  Some system header file is conflicting with STL names, and that has to be breaking code everywhere.

**Comment by Zygo** [comment]
Or...just put  `#undef swap` right after `#undef min`, `#undef max`, `#undef mutex` in include/crucible/btrfs.h.
